using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Simplic.CXUI.BuildTask
{
    /// <summary>
    /// Represents a file, which is generated by some BuildTask and might be used
    /// in another build step
    /// </summary>
    public class GeneratedFile
    {
        /// <summary>
        /// Create generated file
        /// </summary>
        public GeneratedFile()
        {

        }

        /// <summary>
        /// Create generated path
        /// </summary>
        /// <param name="absolutePath">Absolte path to the file</param>
        public GeneratedFile(string absolutePath)
        {
            AbsolutePath = absolutePath;
            Name = Path.GetFileNameWithoutExtension(absolutePath);
            Extension = Path.GetExtension(absolutePath);
            AbsoluteDirectoryPath = Path.GetDirectoryName(absolutePath);
        }

        /// <summary>
        /// Name of the file
        /// </summary>
        public string Name
        {
            get;
            set;
        }

        /// <summary>
        /// Extension of the file
        /// </summary>
        public string Extension
        {
            get;
            set;
        }

        /// <summary>
        /// Absolte (full) directory path
        /// </summary>
        public string AbsoluteDirectoryPath
        {
            get;
            set;
        }

        /// <summary>
        /// Relative directory path
        /// </summary>
        public string RelativeDirectoryPath
        {
            get;
            internal set;
        }

        /// <summary>
        /// Absolte path to the file
        /// </summary>
        public string AbsolutePath
        {
            get;
            internal set;
        }
    }
}
